### ISSUE TITLE
InMemoryAppender Error

### ISSUE THREAD

**Issue by thanneman79** [kchristensen/udm-le#33] opened 2021-04-09 13:56 UTC
Seeing the below in the output, otherwise the script appears to work and a new cert was grabbed and unifi-os restarted.

2021-04-09 09:54:21,904 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-04-09 09:54:22,997 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"

**Comment by kchristensen** [comment] 2021-04-09 14:54
What version of unifi-os are you running?

**Comment by thanneman79** [comment] 2021-04-09 15:24
The controller is running 6.1.7.1

**Comment by kchristensen** [comment] 2021-04-09 15:41
This seems a lot like a java error, I'm not sure it has anything at all to do with udm-le other than being emitted possibly when the unifi-os container restarts.

**Comment by brianveltman** [comment] 2021-04-14 20:51
Having the same issue here.

**Comment by thanneman79** [comment] 2021-04-14 21:22
> This seems a lot like a java error, I'm not sure it has anything at all to do with udm-le other than being emitted possibly when the unifi-os container restarts.

It does seem to be related to the logging facilities. And it doesn't seem to impact functionality.

**Comment by thanneman79** [comment] 2021-04-14 21:23
> Having the same issue here.

Other than the error is it working?

**Comment by brianveltman** [comment] 2021-04-14 21:57
> > Having the same issue here.
> 
> Other than the error is it working?

Unfortunately not. When accessing the controller using the FQDN it will not load all components / pages.
I'm currently on my mobile. Will investigate further later today.

**Comment by brianveltman** [comment] 2021-04-15 12:50
I've checked the error in the browser.
`WebSocket connection to 'wss://unfi.example.com/api/ws/system' failed: 
(anonymous) @ main.1d45b7f6.js:1
`
This may be caused by the fact I have not set up an explicit hostname for the DMP. I can not find such setting anymore with the latest firmware.

**Comment by brianveltman** [comment] 2021-04-15 12:51
> I've checked the error in the browser.
> `WebSocket connection to 'wss://unfi.example.com/api/ws/system' failed: (anonymous) @ main.1d45b7f6.js:1 `
> This may be caused by the fact I have not set up an explicit hostname for the DMP. I can not find such setting anymore with the latest firmware.

Just to be clear. Yes, the certificate from let's encrypt has been issued and applied to the DMP successfully.

**Comment by kchristensen** [comment] 2021-06-22 16:59
I'm going to to close this out -- that `InMemoryAppender` error is a red herring and has no impact on the ability of udm-le to do it's thing.

**Closed by kchristensen** 2021-06-22 16:59 UTC
